version: "3.9"
services:
  mysql:
    image: mysql:8.0.23
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    network_mode: "host"
  mongo:
    image: mongo:3.6.22
    volumes:
      - ./data/mongo:/data/db
    network_mode: "host"
  rabbitmq:
    image: rabbitmq:3.8.14
    network_mode: "host"