version: "3.9"
services:
  mysql:
    image: mysql:8.0.23
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    ports:
      - 3306:3306
  mongo:
    image: mongo:3.6.22
    volumes:
      - ./data/mongo:/data/db
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3.8.14
    ports:
      - 5672:5672
      - 15672:15672
  server:
    image: andreajuanmaurjc/server
    environment:
      - SERVER_PORT=3000
      - SERVER_MYSQL_HOST=mysql
      - SERVER_RABBIT_HOST=amqp://guest:guest@rabbitmq:5672
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - mysql
      - rabbitmq
    command: ["./wait-for-it.sh", "mysql:3306", "--", "node", "src/server.js"]
  toposervice:
    image: andreajuanmaurjc/toposervice
    environment: 
      - TOPOSERVICE_MONGO_HOST=mongo
      - TOPOSERVICE_MONGO_PORT=27017
      - TOPOSERVICE_MONGO_DATABASE=topo
    ports:
      - 8080:8080
    depends_on:
      - mongo
  planner:
    image: andreajuanmaurjc/planner
    environment: 
      - WEATHERSERVICE_URL=static://weatherservice:9090
      - TOPOSERVICE_RABBIT_HOST=rabbitmq
      - TOPOSERVICE_RABBIT_PORT=5672
      - TOPOSERVICE_RABBIT_USERNAME=guest
      - TOPOSERVICE_RABBIT_PASSWORD=guest
      - TOPOSERVICE_HOST=toposervice
      - TOPOSERVICE_PORT=8080
    depends_on:
      - rabbitmq
  weatherservice:
    image: andreajuanmaurjc/weatherservice:v1
    environment:
      - GRPC_HOST=weatherservice
    ports:
      - 9090:9090