version: "3.9"
services:
  mysql:
    image: mysql:8.0.23
    # volumes:
    #   - ./server/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=eoloplantsDB
    ports:
      - 3306:3306
  # mongo:
  #   image: mongo:3.6.22
  #   volumes:
  #     - ./mongo:/data/db
  #   ports:
  #     - 27017:27017
  rabbit:
    image: rabbitmq:3.8.14
    ports:
      - 5672:5672
      - 15672:15672
  server:
    image: andreajuanmaurjc/server
    environment:
      - MYSQL_HOST=mysql
      - RABBIT_HOST=rabbit
    ports:
      - 3000:3000
    depends_on:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306", "--", "node", "src/server.js"]